{% set name = "tensorflow-recommenders" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorflow-recommenders-{{ version }}.tar.gz
  sha256: e71fe52104865ed75794e1d609b2c0dcaa0c70cd0ee23abd9d092a246df86e53

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py >=0.1.6
    - tensorflow >=2.9.0  # [not darwin]
    - tensorflow-macos >=2.9.0  # [darwin]

test:
  imports:
    - tensorflow_recommenders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tensorflow/recommenders
  summary: Tensorflow Recommenders, a TensorFlow library for recommender systems.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MLnick
